import type { z } from 'zod/v4';
import type { AskDesignRequestSchema, DesignAnalysisRequestSchema, DesignChangeRequestSchema } from './designAssistantSchema';

export function analysisPrompt(request: z.infer<typeof DesignAnalysisRequestSchema>) {
  return `Analyze this user-owned game design skeleton. Return strengths and a small number of concrete structural issues. Do not propose changes yet. Focus on loops, resources, progression, and redundant or disconnected design. Gameplay edges (produces, consumes, requires, unlocks, improves, leads_to) describe flow, dependency, or progression. The contains edge is different: parent → child decomposition only, not gameplay flow.\nPROJECT\n${JSON.stringify(request.project)}\nSKELETON\n${JSON.stringify(request.skeleton)}`;
}

export function changePrompt(request: z.infer<typeof DesignChangeRequestSchema>) {
  return `Propose one focused, atomic design change set for the selected issue. The user will review every operation. You may add, update, or remove nodes and edges; do not add unnecessary features. Gameplay edges (produces, consumes, requires, unlocks, improves, leads_to) express game behavior; contains expresses parent → child subsystem decomposition only. Use only IDs already in the skeleton for updates/removals. For REMOVE_EDGE and UPDATE_EDGE, copy the exact canonical edge ID from SKELETON.edges[].id; never invent an edge ID. For new IDs use short unique IDs. If removing a node, explicitly remove or replace all of its attached edges. UPDATE_NODE is a complete replacement of label, gameType, importance, and description; use description null only to clear that description.\nPROJECT\n${JSON.stringify(request.project)}\nSKELETON\n${JSON.stringify(request.skeleton)}\nSELECTED ISSUE\n${JSON.stringify(request.issue)}`;
}

export function askDesignPrompt(request: z.infer<typeof AskDesignRequestSchema>) {
  return `You are an intent-driven game-design editing assistant. Interpret the user's instruction against the complete, current canonical skeleton. Return either one focused, atomic changeSet or exactly one focused clarificationQuestion when a material ambiguity prevents a safe design choice. If clarificationQuestion is non-null, changeSet must be null. If a changeSet is non-null, clarificationQuestion must be null. Explain your interpretation briefly. The user owns the design and approves every change; never claim to apply it. Gameplay edges (produces, consumes, requires, unlocks, improves, leads_to) describe gameplay flow, dependency, or progression. contains means parent → child subsystem decomposition only. Use contains for requested subsystem details where appropriate, rather than pretending they are gameplay progression. Use only canonical node IDs and edge IDs for updates/removals. For REMOVE_EDGE and UPDATE_EDGE, copy an exact SKELETON.edges[].id; never invent one. New node/edge IDs must be short and unique. Do not use visual positions as design meaning.\nPROJECT\n${JSON.stringify(request.project)}\nSKELETON\n${JSON.stringify(request.skeleton)}\nUSER INSTRUCTION\n${request.instruction}\nCLARIFICATION ANSWER\n${request.clarificationAnswer ?? 'None'}`;
}
